import { VisualMappingState, VisualSlotItem } from "./VisualDefinitions";

export function generateChartCode(type: string, mapping: VisualMappingState, columns: string[], title: string): string {
  // Helper to sanitize variable names
  const clean = (name: string) => name.replace(/[^a-zA-Z0-9]/g, '_');

  const getSlot = (id: string): VisualSlotItem[] => mapping[id] || [];
  
  const xAxis = getSlot('xAxis')[0]?.name || getSlot('cols')[0]?.name || columns[0] || '';
  const yAxisFirst = getSlot('yAxis')[0]?.name || getSlot('values')[0]?.name || columns[1] || '';
  const values = getSlot('yAxis').length > 0 ? getSlot('yAxis') : getSlot('values');
  
  // Basic checks
  if (!xAxis && !yAxisFirst) {
    return `function Chart() { return <div style={{padding:20,textAlign:'center'}}>Faltan campos para renderizar.</div>; }`;
  }

  // Pre-process Data (Agrupaciones/Agregaciones básicas en JSX)
  const codeHeader = `// Auto-generated by DataCanvas O.S.\n// title: ${title}\n
function Chart() {
  // Configuración de Series
  const xAxis = ${JSON.stringify(xAxis)};
  const series = ${JSON.stringify(values.map(v => ({ key: v.name, agg: v.agg, name: clean(v.name) })))};
  
  // Opcional: Procesamiento de datos si hay agregados (sum, avg)
  // Aquí React puede agrupar 'data' basado en 'xAxis' y 'series'
  const processedData = React.useMemo(() => {
    if (!xAxis || series.length === 0) return data;
    const grouped = {};
    data.forEach(row => {
      const xVal = row[xAxis] ?? 'N/A';
      if (!grouped[xVal]) {
        grouped[xVal] = { [xAxis]: xVal };
        series.forEach(s => grouped[xVal][s.name] = { sum: 0, count: 0, max: -Infinity, min: Infinity, vals: new Set() });
      }
      series.forEach(s => {
        const rawVal = row[s.key];
        const val = Number(rawVal);
        const isNum = !isNaN(val) && rawVal !== null && rawVal !== '';

        if (isNum) {
          grouped[xVal][s.name].sum += val;
          if (val > grouped[xVal][s.name].max) grouped[xVal][s.name].max = val;
          if (val < grouped[xVal][s.name].min) grouped[xVal][s.name].min = val;
        }

        grouped[xVal][s.name].count += 1;
        grouped[xVal][s.name].vals.add(rawVal);
      });
    });
    return Object.values(grouped).map(g => {
      const out = { [xAxis]: g[xAxis] };
      series.forEach(s => {
        if (s.agg === 'avg') out[s.name] = g[s.name].count ? g[s.name].sum / g[s.name].count : 0;
        else if (s.agg === 'max') out[s.name] = g[s.name].max === -Infinity ? 0 : g[s.name].max;
        else if (s.agg === 'min') out[s.name] = g[s.name].min === Infinity ? 0 : g[s.name].min;
        else if (s.agg === 'count') out[s.name] = g[s.name].count;
        else if (s.agg === 'distinct') out[s.name] = g[s.name].vals.size;
        else out[s.name] = g[s.name].sum; // default to sum
      });
      return out;
    });
  }, [data]);

  const colors = ["#4f46e5", "#10b981", "#f59e0b", "#ef4444", "#8b5cf6", "#ec4899", "#14b8a6"];
`;

  const commonFooter = `
    </div>
  );
}`;

  let content = "";
  
  switch (type) {
    case 'bar':
    case 'bar-stacked':
    case 'bar-h':
    case 'line':
    case 'area':
    case 'combo':
      const isStacked = type === 'bar-stacked';
      const isHorizontal = type === 'bar-h';
      const ChartComp = type.includes('bar') ? 'BarChart' : type === 'area' ? 'AreaChart' : type === 'combo' ? 'ComposedChart' : 'LineChart';
      const LineComp = type === 'area' ? 'Area' : type === 'combo' ? 'Bar' : 'Line'; // combo uses Bar mostly with Line
      
      content = `
  return (
    <div style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column' }}>
      <h2 style={{ fontWeight: 700, fontSize: 14, marginBottom: 8, color: 'inherit' }}>{${JSON.stringify(title)}}</h2>
      <ResponsiveContainer width="100%" height="100%" minHeight={250}>
        <${ChartComp} data={processedData} layout="${isHorizontal ? 'vertical' : 'horizontal'}" margin={{top:10,right:30,left:0,bottom:0}}>
          <CartesianGrid strokeDasharray="3 3" opacity={0.2} />
          ${isHorizontal ? `
          <XAxis type="number" tick={{ fontSize: 10 }} />
          <YAxis dataKey={xAxis} type="category" tick={{ fontSize: 10 }} width={80} />
          ` : `
          <XAxis dataKey={xAxis} tick={{ fontSize: 10 }} />
          <YAxis tick={{ fontSize: 10 }} />
          `}
          <Tooltip contentStyle={{ backgroundColor: '#1e293b', border: 'none', borderRadius: 8, color: '#f8fafc', fontSize: 12 }} />
          <Legend wrapperStyle={{ fontSize: 11 }} />
          {series.map((s, i) => (
            <${type==='line'?'Line':type==='area'?'Area':'Bar'} 
              key={s.name} 
              dataKey={s.name} 
              name={s.key + " (" + s.agg + ")"}
              fill={colors[i % colors.length]} 
              stroke={colors[i % colors.length]}
              strokeWidth={2}
              stackId="${isStacked ? 'a' : ''}" 
              radius={${isStacked || type==='line' || type==='area' ? '0' : '[4,4,0,0]'}} 
            />
          ))}
          ${type==='combo' && getSlot('yAxisSec').length > 0 ? getSlot('yAxisSec').map((s,i) => `
            <Line key={"sec_"+Math.random()} type="monotone" dataKey=${JSON.stringify(s.name)} name=${JSON.stringify(s.name)} stroke="#ef4444" strokeWidth={3} />
          `).join('') : ''}
        </${ChartComp}>
      </ResponsiveContainer>`;
      break;

    case 'pie':
    case 'donut':
      const pieCat = xAxis || getSlot('legend')[0]?.name;
      const pieVal = values[0];
      if (!pieCat || !pieVal) {
        content = `return <div style={{padding:20}}>Arrastra campos a Eje Y / Leyenda</div>;`;
        break;
      }
      content = `
  const pieData = processedData;
  return (
    <div style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column' }}>
      <h2 style={{ fontWeight: 700, fontSize: 14, marginBottom: 8 }}>{${JSON.stringify(title)}}</h2>
      <ResponsiveContainer width="100%" height="100%" minHeight={250}>
        <PieChart>
          <Tooltip contentStyle={{ backgroundColor: '#1e293b', border: 'none', borderRadius: 8, color: '#f8fafc', fontSize: 12 }} />
          <Legend wrapperStyle={{ fontSize: 11 }} />
          <Pie
            data={pieData}
            dataKey="${clean(pieVal.name)}"
            nameKey="${pieCat}"
            cx="50%" cy="50%"
            innerRadius={${type === 'donut' ? 60 : 0}}
            outerRadius={80}
            paddingAngle={${type === 'donut' ? 5 : 0}}
            label
          >
            {pieData.map((_, index) => <Cell key={"cell-"+index} fill={colors[index % colors.length]} />)}
          </Pie>
        </PieChart>
      </ResponsiveContainer>`;
      break;
      
    case 'card':
    case 'kpi':
      const cardVal = values[0];
      if (!cardVal) {
        content = `return <div>Arrastra un Valor</div>;`;
        break;
      }
      content = `
  const cardAggValue = React.useMemo(() => {
    let sum = 0, count = 0, min = Infinity, max = -Infinity;
    const vals = new Set();
    data.forEach(row => {
      const rawVal = row["${cardVal.name}"];
      const val = Number(rawVal);
      const isNum = !isNaN(val) && rawVal !== null && rawVal !== '';

      if (isNum) {
        sum += val;
        if (val < min) min = val;
        if (val > max) max = val;
      }
      count++;
      vals.add(rawVal);
    });

    const agg = "${cardVal.agg}";
    if (agg === 'avg') return count ? sum / count : 0;
    if (agg === 'max') return max === -Infinity ? 0 : max;
    if (agg === 'min') return min === Infinity ? 0 : min;
    if (agg === 'count') return count;
    if (agg === 'distinct') return vals.size;
    return sum;
  }, [data]);

  const formatted = new Intl.NumberFormat('en-US', { notation: "compact", compactDisplay: "short" }).format(cardAggValue);
  return (
    <div style={{ padding: 24, display: 'flex', flexDirection: 'column', height: '100%', justifyContent: 'center' }}>
      <h3 style={{ fontSize: 12, opacity: 0.6, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 4 }}>
        ${cardVal.name} (${cardVal.agg})
      </h3>
      <div style={{ fontSize: 48, fontWeight: 900, color: '#4f46e5', lineHeight: 1 }}>
        {formatted}
      </div>
      ${type === 'kpi' && getSlot('target')[0] ? `
        <div style={{ fontSize: 12, marginTop: 8, color: '#10b981', fontWeight: 700 }}>
          ▶ Meta: ${getSlot('target')[0].name}
        </div>
      ` : ''}
      `;
      break;

    case 'table': {
      const dimFields = [...getSlot('cols'), ...getSlot('xAxis')].map(f => f.name);
      const valFields = [...getSlot('values'), ...getSlot('yAxis')];
      const allDims = dimFields.length > 0 ? Array.from(new Set(dimFields)) : columns.slice(0, 2);
      const allVals = valFields.length > 0 ? valFields : [];

      const aggCode = allVals.map(v => {
        const key = JSON.stringify(v.name);
        switch(v.agg) {
          case 'avg': return `{ key: ${key}, label: ${JSON.stringify(v.name + ' (AVG)')}, fn: (rows) => { const n = rows.map(r=>Number(r[${key}])||0); return n.length ? n.reduce((a,b)=>a+b,0)/n.length : 0; } }`;
          case 'count': return `{ key: ${key}, label: ${JSON.stringify(v.name + ' (CNT)')}, fn: (rows) => rows.length }`;
          case 'distinct': return `{ key: ${key}, label: ${JSON.stringify(v.name + ' (DCNT)')}, fn: (rows) => new Set(rows.map(r=>r[${key}])).size }`;
          case 'max': return `{ key: ${key}, label: ${JSON.stringify(v.name + ' (MAX)')}, fn: (rows) => rows.length ? Math.max(...rows.map(r=>Number(r[${key}])||0)) : 0 }`;
          case 'min': return `{ key: ${key}, label: ${JSON.stringify(v.name + ' (MIN)')}, fn: (rows) => rows.length ? Math.min(...rows.map(r=>Number(r[${key}])||0)) : 0 }`;
          default: return `{ key: ${key}, label: ${JSON.stringify(v.name + ' (SUM)')}, fn: (rows) => rows.reduce((a,r)=>a+(Number(r[${key}])||0),0) }`;
        }
      }).join(',\n    ');

      content = `
  const _dims = ${JSON.stringify(allDims)};
  const _measures = [${aggCode}];
  const tableData = React.useMemo(() => {
    if (_measures.length === 0) return data.slice(0, 200);
    const grouped = {};
    data.forEach(row => {
      const key = _dims.map(f => String(row[f] ?? 'N/A')).join('|||');
      if (!grouped[key]) grouped[key] = { _d: {}, _r: [] };
      _dims.forEach(f => { grouped[key]._d[f] = row[f]; });
      grouped[key]._r.push(row);
    });
    return Object.values(grouped).map(g => {
      const out = { ...g._d };
      _measures.forEach(m => { out[m.label] = m.fn(g._r); });
      return out;
    }).slice(0, 500);
  }, [data]);
  const _cols = _measures.length > 0 ? [..._dims, ..._measures.map(m => m.label)] : _dims;
  const _fmt = v => typeof v === 'number' ? new Intl.NumberFormat('en-US', { notation: 'compact' }).format(v) : String(v ?? '');
  return (
    <div style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column' }}>
      <h2 style={{ fontWeight: 700, fontSize: 14, marginBottom: 8, flexShrink: 0, color: 'inherit' }}>{${JSON.stringify(title)}}</h2>
      <div style={{ flex: 1, overflow: 'auto', border: '1px solid #e2e8f0', borderRadius: 8 }}>
        <table style={{ width: '100%', fontSize: 12, borderCollapse: 'collapse' }}>
          <thead style={{ background: '#f8fafc', position: 'sticky', top: 0, zIndex: 1 }}>
            <tr>
              {_cols.map((c, i) => (
                <th key={c} style={{ padding: '8px 12px', textAlign: i < _dims.length ? 'left' : 'right', borderBottom: '2px solid #cbd5e1', whiteSpace: 'nowrap', color: i < _dims.length ? '#334155' : '#4f46e5' }}>{c}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {tableData.map((row, i) => (
              <tr key={i} style={{ borderBottom: '1px solid #f1f5f9', background: i % 2 ? '#fafafa' : 'transparent' }}>
                {_cols.map((c, ci) => (
                  <td key={c} style={{ padding: '7px 12px', whiteSpace: 'nowrap', textAlign: ci < _dims.length ? 'left' : 'right', fontWeight: ci >= _dims.length ? 600 : 400 }}>{_fmt(row[c])}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>`;
      break;
    }

    case 'matrix': {
      const rowField = getSlot('rows')[0]?.name || getSlot('yAxis')[0]?.name;
      const colField = getSlot('cols')[0]?.name;
      const valItems = getSlot('values').length > 0 ? getSlot('values') : getSlot('yAxisSec');
      
      if (!rowField || !colField || valItems.length === 0) {
        content = `return <div style={{padding:20,textAlign:'center',color:'#64748b',fontSize:12}}>
          <div style={{fontSize:14,fontWeight:700,marginBottom:10}}>&#x1F4CA; Matriz Din\u00e1mica</div>
          <div style={{textAlign:'left',lineHeight:1.8}}>
            Necesitas configurar:<br/>
            \u2022 <b>Filas (Y)</b>: Campo de agrupaci\u00f3n vertical<br/>
            \u2022 <b>Columnas</b>: Campo de agrupaci\u00f3n horizontal<br/>
            \u2022 <b>Valores</b>: 1 o m\u00e1s medidas (SUM, AVG, etc.)
          </div>
        </div>;`;
        break;
      }

      const valItemsJson = JSON.stringify(valItems.map(v => ({ name: v.name, agg: v.agg || 'sum', label: `${v.name} [${(v.agg||'sum').toUpperCase()}]` })));
      const rf = JSON.stringify(rowField);
      const cf = JSON.stringify(colField);

      content = `
  const _rf = ${rf};
  const _cf = ${cf};
  const _vi = ${valItemsJson};
  const _fmt = n => new Intl.NumberFormat('en-US', { notation: 'compact' }).format(n);

  const _agg = (acc, vi) => {
    if (!acc || acc.count === 0) return '-';
    switch(vi.agg) {
      case 'avg': return _fmt(acc.sum / acc.count);
      case 'count': return _fmt(acc.count);
      case 'distinct': return _fmt(new Set(acc.vals).size);
      case 'max': return _fmt(acc.max === -Infinity ? 0 : acc.max);
      case 'min': return _fmt(acc.min === Infinity ? 0 : acc.min);
      default: return _fmt(acc.sum);
    }
  };

  const _merge = (a, b) => ({
    sum: a.sum + b.sum, count: a.count + b.count,
    min: Math.min(a.min, b.min), max: Math.max(a.max, b.max),
    vals: [...a.vals, ...b.vals]
  });
  const _zero = () => ({ sum: 0, count: 0, min: Infinity, max: -Infinity, vals: [] });

  const pivot = React.useMemo(() => {
    const rowKeys = new Set();
    const colKeys = new Set();
    const map = {};
    data.forEach(d => {
      const r = String(d[_rf] ?? 'N/A');
      const c = String(d[_cf] ?? 'N/A');
      rowKeys.add(r); colKeys.add(c);
      if (!map[r]) map[r] = {};
      if (!map[r][c]) map[r][c] = {};
      _vi.forEach(vi => {
        const v = Number(d[vi.name]) || 0;
        if (!map[r][c][vi.name]) map[r][c][vi.name] = _zero();
        map[r][c][vi.name].sum += v;
        map[r][c][vi.name].count++;
        if (v < map[r][c][vi.name].min) map[r][c][vi.name].min = v;
        if (v > map[r][c][vi.name].max) map[r][c][vi.name].max = v;
        map[r][c][vi.name].vals.push(String(d[vi.name]));
      });
    });
    return { rows: Array.from(rowKeys).sort(), cols: Array.from(colKeys).sort(), map };
  }, [data]);

  const rowTot = (r, vi) => pivot.cols.reduce((acc, c) => _merge(acc, map[r]?.[c]?.[vi.name] || _zero()), _zero());
  const grandTot = (vi) => pivot.rows.reduce((acc, r) => _merge(acc, rowTot(r, vi)), _zero());
  const { map } = pivot;

  return (
    <div style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column' }}>
      <h2 style={{ fontWeight: 700, fontSize: 13, marginBottom: 6, flexShrink: 0, color: 'inherit' }}>{${JSON.stringify(title)}}</h2>
      <div style={{ flex: 1, overflow: 'auto', border: '1px solid #e2e8f0', borderRadius: 8 }}>
        <table style={{ width: '100%', fontSize: 11, borderCollapse: 'collapse' }}>
          <thead style={{ position: 'sticky', top: 0, zIndex: 2 }}>
            <tr style={{ background: '#1e293b', color: '#e2e8f0' }}>
              <th rowSpan={_vi.length > 1 ? 2 : 1} style={{ padding: '8px 12px', textAlign: 'left', borderRight: '2px solid #334155', minWidth: 110 }}>
                {_rf}
              </th>
              {pivot.cols.map(c => (
                <th key={c} colSpan={_vi.length} style={{ padding: '6px 10px', textAlign: 'center', borderRight: '1px solid #334155', borderBottom: _vi.length > 1 ? '1px solid #4b5563' : undefined }}>
                  {c}
                </th>
              ))}
              <th colSpan={_vi.length} style={{ padding: '6px 10px', textAlign: 'center', background: '#4338ca' }}>
                Total
              </th>
            </tr>
            {_vi.length > 1 && (
              <tr style={{ background: '#334155', color: '#94a3b8' }}>
                {pivot.cols.flatMap(c => _vi.map(vi => (
                  <th key={c + vi.name} style={{ padding: '4px 8px', textAlign: 'right', fontSize: 10, whiteSpace: 'nowrap', borderRight: '1px solid #4b5563' }}>
                    {vi.agg.toUpperCase()}
                  </th>
                )))}
                {_vi.map(vi => (
                  <th key={'t_' + vi.name} style={{ padding: '4px 8px', textAlign: 'right', fontSize: 10, background: '#3730a3', color: '#c7d2fe' }}>
                    {vi.agg.toUpperCase()}
                  </th>
                ))}
              </tr>
            )}
          </thead>
          <tbody>
            {pivot.rows.map((r, ri) => (
              <tr key={ri} style={{ borderBottom: '1px solid #f1f5f9', background: ri % 2 ? '#fafbff' : 'transparent' }}>
                <td style={{ padding: '7px 12px', fontWeight: 700, borderRight: '2px solid #e2e8f0', whiteSpace: 'nowrap' }}>{r}</td>
                {pivot.cols.flatMap(c => _vi.map(vi => (
                  <td key={c + vi.name} style={{ padding: '6px 10px', textAlign: 'right', borderRight: '1px solid #f1f5f9', color: map[r]?.[c]?.[vi.name]?.count > 0 ? '#0f172a' : '#cbd5e1' }}>
                    {_agg(map[r]?.[c]?.[vi.name], vi)}
                  </td>
                )))}
                {_vi.map(vi => (
                  <td key={'rt_' + vi.name} style={{ padding: '6px 10px', textAlign: 'right', fontWeight: 700, background: '#eff0ff', color: '#4338ca' }}>
                    {_agg(rowTot(r, vi), vi)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr style={{ background: '#1e293b', color: '#fff', fontWeight: 700, borderTop: '2px solid #334155' }}>
              <td style={{ padding: '7px 12px', borderRight: '2px solid #334155' }}>Gran Total</td>
              {pivot.cols.flatMap(c => _vi.map(vi => {
                const acc = pivot.rows.reduce((a, r) => _merge(a, map[r]?.[c]?.[vi.name] || _zero()), _zero());
                return <td key={c + vi.name + 'gf'} style={{ padding: '6px 10px', textAlign: 'right', borderRight: '1px solid #334155' }}>{_agg(acc, vi)}</td>;
              }))}
              {_vi.map(vi => (
                <td key={'gt_' + vi.name} style={{ padding: '6px 10px', textAlign: 'right', background: '#3730a3', color: '#e0e7ff' }}>
                  {_agg(grandTot(vi), vi)}
                </td>
              ))}
            </tr>
          </tfoot>
        </table>
      </div>`;
      break;
    }

     case 'slicer': {
      const field = getSlot('cols')[0]?.name || getSlot('xAxis')[0]?.name || getSlot('yAxis')[0]?.name || Object.values(mapping).flat()[0]?.name;
      if (!field) {
        return `function Chart() { return <div style={{padding:20,textAlign:'center',opacity:0.5,fontSize:12}}>Arrastra un campo al slot de <b>Columnas</b> para activar el filtro.</div>; }`;
      }
      const f = JSON.stringify(field);
      return `// Smart Slicer — DataCanvas O.S.
function Chart() {
  const FF = ${f};
  const win = window;
  const IS_DATE = React.useMemo(() => {
    const s = data.slice(0,30).map(d=>d[FF]).filter(Boolean);
    return s.length > 0 && s.filter(v => !isNaN(Date.parse(String(v)))).length / s.length > 0.6;
  }, [data]);
  const options = React.useMemo(() =>
    Array.from(new Set(data.map(d=>String(d[FF])))).filter(v=>v&&v!=='null'&&v!=='undefined').sort()
  , [data]);
  const getActive = () => { const f=(win.__dashboardFilters||{})[FF]; return Array.isArray(f)?f:[]; };
  const [sel, setSel] = React.useState(()=>getActive());
  const [search, setSearch] = React.useState('');
  const [expanded, setExpanded] = React.useState(true);
  const [dateFrom, setDateFrom] = React.useState('');
  const [dateTo, setDateTo] = React.useState('');
  const filtered = search ? options.filter(o=>o.toLowerCase().includes(search.toLowerCase())) : options;
  const isAll = sel.length === 0;
  const label = isAll ? 'Todos (' + options.length + ')' : sel.length === 1 ? sel[0] : sel.length + ' de ' + options.length;
  const dispatch = () => win.dispatchEvent(new Event('dashboard-filter'));
  const toggle = (val) => {
    win.__dashboardFilters = win.__dashboardFilters||{};
    let cur = [...((win.__dashboardFilters[FF])||[])].filter(v=>typeof v==='string');
    if(val==='__all__'){delete win.__dashboardFilters[FF];setSel([]);}
    else if(cur.includes(val)){cur=cur.filter(v=>v!==val);win.__dashboardFilters[FF]=cur.length?cur:undefined;if(!cur.length)delete win.__dashboardFilters[FF];setSel(cur);}
    else{cur=[...cur,val];win.__dashboardFilters[FF]=cur;setSel(cur);}
    dispatch();
  };
  const applyDate = (from, to) => {
    win.__dashboardFilters=win.__dashboardFilters||{};
    if(!from&&!to){delete win.__dashboardFilters[FF];}
    else{win.__dashboardFilters[FF]={__dateRange:true,from,to};}
    dispatch();
  };
  const hdr = {fontSize:10,fontWeight:800,textTransform:'uppercase',letterSpacing:1,color:'#6366f1',display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:6,cursor:'pointer',userSelect:'none'};
  if(IS_DATE) return (
    <div style={{width:'100%',height:'100%',display:'flex',flexDirection:'column',padding:'6px 2px',boxSizing:'border-box',gap:8}}>
      <div style={hdr}><span>&#128197; {FF}</span></div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}>
        <div>
          <div style={{fontSize:10,fontWeight:700,color:'#64748b',marginBottom:3}}>DESDE</div>
          <input type="date" value={dateFrom} onChange={e=>{setDateFrom(e.target.value);applyDate(e.target.value,dateTo);}}
            style={{width:'100%',padding:'6px 6px',border:'1.5px solid '+(dateFrom?'#6366f1':'#e2e8f0'),borderRadius:6,fontSize:11,outline:'none',boxSizing:'border-box',background:dateFrom?'#eff6ff':'#fff',cursor:'pointer'}} />
        </div>
        <div>
          <div style={{fontSize:10,fontWeight:700,color:'#64748b',marginBottom:3}}>HASTA</div>
          <input type="date" value={dateTo} onChange={e=>{setDateTo(e.target.value);applyDate(dateFrom,e.target.value);}}
            style={{width:'100%',padding:'6px 6px',border:'1.5px solid '+(dateTo?'#6366f1':'#e2e8f0'),borderRadius:6,fontSize:11,outline:'none',boxSizing:'border-box',background:dateTo?'#eff6ff':'#fff',cursor:'pointer'}} />
        </div>
      </div>
      {(dateFrom||dateTo)&&<div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>
        <span style={{fontSize:11,color:'#6366f1',fontWeight:700}}>{dateFrom||'...'} &#x2192; {dateTo||'...'}</span>
        <button onClick={()=>{setDateFrom('');setDateTo('');applyDate('','');}} style={{fontSize:10,color:'#ef4444',background:'none',border:'none',cursor:'pointer',fontWeight:700}}>&#x2715; Limpiar</button>
      </div>}
    </div>
  );
  return (
    <div style={{width:'100%',height:'100%',display:'flex',flexDirection:'column',padding:'6px 2px',boxSizing:'border-box',overflow:'hidden'}}>
      <div style={hdr} onClick={()=>setExpanded(e=>!e)}>
        <span>&#x1F5C3;&#xFE0F; {FF}</span>
        <span style={{fontSize:11,color:'#94a3b8',transform:expanded?'rotate(0deg)':'rotate(-90deg)',display:'inline-block',transition:'transform 0.2s'}}>&#x25BC;</span>
      </div>
      {expanded&&<>
        <div style={{fontSize:11,fontWeight:700,color:'#6366f1',padding:'3px 8px',background:'#eef2ff',borderRadius:8,marginBottom:4}}>{label}</div>
        <input type="text" placeholder="Buscar..." value={search} onChange={e=>setSearch(e.target.value)}
          style={{padding:'5px 8px',fontSize:11,border:'1px solid #e2e8f0',borderRadius:6,outline:'none',marginBottom:4,width:'100%',boxSizing:'border-box',background:'#fafafa'}} />
        <div style={{flex:1,overflowY:'auto',display:'flex',flexDirection:'column',gap:1}}>
          <div onClick={()=>toggle('__all__')} style={{padding:'4px 8px',borderRadius:5,cursor:'pointer',fontSize:11,fontWeight:isAll?800:500,background:isAll?'#6366f1':'transparent',color:isAll?'#fff':'#374151',userSelect:'none'}}>
            &#x2713; Todos
          </div>
          {filtered.map(o=>{const a=sel.includes(o);return(
            <div key={o} onClick={()=>toggle(o)} style={{padding:'4px 8px',borderRadius:5,cursor:'pointer',fontSize:11,fontWeight:a?700:400,background:a?'#e0e7ff':'transparent',color:a?'#4338ca':'#374151',display:'flex',alignItems:'center',gap:5,userSelect:'none'}}>
              <span style={{width:12,height:12,border:'2px solid '+(a?'#6366f1':'#cbd5e1'),borderRadius:3,background:a?'#6366f1':'transparent',display:'inline-flex',alignItems:'center',justifyContent:'center',fontSize:8,color:'#fff',flexShrink:0}}>{a?'✓':''}</span>
              <span style={{flex:1,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{o}</span>
            </div>
          );})}
        </div>
      </>}
    </div>
  );
}`;
    }

    default:
      content = `
  return (
    <div style={{ padding: 20 }}>
      Visual no soportado completamente aún. 
    </div>
  `;
      break;
  }

  return codeHeader + content + commonFooter;
}
